name: Build LOVE2D package for MacOS

on:
  push:
    branches:
      - main

jobs:
  deploy-on-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Built .love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: ./snake/
          package-path: ./SNEK.love

      - name: Build MacOS binary
        uses: love-action/love-actions-macos-portable@v1.1.2
        with:
          love-package: ./SNEK.love
          product-name: SNEK
          app-id: SNEK
          output-folder: "./build"

      - name: Upload pkg artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNEK_macOS_portable_pkg
          path: ./build/SNEK_macOS_portable.pkg

      - name: Upload dmg artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNEK_macOS_portable_dmg
          path: ./build/SNEK_macOS_portable.dmg