name: Build LOVE2D package for Windows

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Love actions for Windows
        id: build-packages
        uses: love-actions/love-actions-windows@v1.1.3
        with:
          love-package: ./snek.love
          # icon-path: ./assets/windows/icon.ico
          rc-path: ../.luarc.json
          product-name: snek
          app-id: snek
          output-folder: "./dist"