name: Build LOVE2D package for Windows

on:
  push:
    branches:
      - main

jobs:
  deploy-on-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Built .love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: ./snake/
          package-path: ./SNEK.love

      - name: Build Windows executable
        uses: love-actions/love-actions-windows@v1.1.3
        with:
          love-package: ./SNEK.love
          # icon-path: ./assets/windows/icon.ico
          # rc-path: ../.luarc.json
          product-name: SNEK
          app-id: SNEK
          output-folder: "./build"

      - name: Upload 64-bit artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNEK_Windows_x64
          path: ./build/SNEK_x64.zip

      - name: Upload installer artifact
        uses: actions/upload-artifact@v4
        with:
          name: SNEK_Windows_installer
          path: ./build/SNEK_installer.exe